import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    form: { padding: 20 },
    header: {
        padding: 15,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 10,
    },
    dateSelector: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    dateText: {
        fontSize: 16,
        marginLeft: 5,
        color: '#007bff',
    },
    summaryButton: {
        justifyContent: 'flex-end',
        flexDirection: 'row',
        alignItems: 'center',
    },
    summaryText: {
        fontSize: 16,
        marginLeft: 5,
        color: '#007bff',
    },
    loader: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    content: {
        flex: 1,
        padding: 15,
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    list: {
        padding: 15,
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 8,
        padding: 15,
        marginBottom: 15,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    statTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginLeft: 5,
        color: '#555',
    },
    statValue: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#333',
    },
    statusIndicatorContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    statusBarBackground: {
        flex: 1,
        height: 16,
        backgroundColor: '#eee',
        borderRadius: 8,
        overflow: 'hidden',
    },
    statusBarFill: {
        height: '100%',
    },
    statusPercentage: {
        fontWeight: 'bold',
        marginLeft: 10,
        width: 50,
        textAlign: 'right',
    },
    completionText: {
        fontSize: 14,
        color: '#666',
    },
    pendingItem: {
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        paddingVertical: 10,
    },
    pendingItemContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    pendingDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: '#FF9800',
        marginRight: 10,
    },
    pendingName: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    pendingRA: {
        fontSize: 14,
        color: '#666',
    },
    pendingQuantity: {
        fontSize: 14,
        color: '#666',
        marginTop: 2,
    },
    allCompleteText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#4CAF50',
        marginTop: 10,
        textAlign: 'center',
    },
    noDataText: {
        fontSize: 16,
        color: '#999',
        marginTop: 10,
        textAlign: 'center',
    },
    statHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    studentInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    studentRA: {
        fontSize: 14,
        color: '#666',
    },
    deliveryTime: {
        fontSize: 12,
        color: '#999',
        marginTop: 2,
    },
    deliveryStatus: {
        marginLeft: 10,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    lunchCount: {
        backgroundColor: '#e6f3ff',
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 12,
        color: '#007bff',
        fontWeight: 'bold',
    },
    cardActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginTop: 5,
    },
    editButton: {
        backgroundColor: '#007bff',
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 4,
        marginRight: 10,
    },
    deleteButton: {
        backgroundColor: '#dc3545',
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 4,
    },
    buttonText: {
        color: '#fff',
        fontWeight: 'bold',
        marginLeft: 5,
    },
    emptyText: {
        fontSize: 16,
        color: '#999',
        textAlign: 'center',
        marginTop: 10,
    },
    addButton: {
        position: 'absolute',
        right: 20,
        bottom: 20,
        backgroundColor: '#007bff',
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: '#fff',
        margin: 20,
        borderRadius: 10,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        maxHeight: '80%',
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    completionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#555',
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: 'bold',
    },
    label: { fontSize: 16, fontWeight: 'bold', marginBottom: 5, color: '#333' },
    studentsList: {
        maxHeight: 200,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#eee',
        borderRadius: 5,
    },
    studentItem: {
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    studentItemContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    studentItemImage: {
        width: 30,
        height: 30,
        borderRadius: 15,
        marginRight: 10,
    },
    studentItemName: {
        fontSize: 14,
        fontWeight: 'bold',
    },
    studentItemRA: {
        fontSize: 12,
        color: '#666',
    },
    studentImage: {
        width: 40,
        height: 40,
        borderRadius: 20,
        marginRight: 10,
    },
    noImage: {
        backgroundColor: '#f0f0f0',
        justifyContent: 'center',
        alignItems: 'center',
    },
    studentName: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    selectedStudentContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f8ff',
        padding: 10,
        borderRadius: 5,
        marginBottom: 15,
    },
    modalDateContainer: {
        backgroundColor: '#f0f0f0',
        borderRadius: 5,
        padding: 10,
        marginBottom: 20,
    },
    datePickerContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 16,
        borderBottomColor: '#e0e0e0',
        backgroundColor: '#fff',
    },
    modalDateText: {
        fontSize: 16,
    },
    input: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 5,
        padding: 10,
        marginBottom: 15,
        fontSize: 16,
    },
    photoButton: {
        alignItems: 'center',
        marginBottom: 20,
    },
    photoContainer: {
        width: 150,
        height: 150,
        borderRadius: 75,
        backgroundColor: '#f0f0f0',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#ddd',
        overflow: 'hidden',
    },
    photo: {
        width: 150,
        height: 150,
        borderRadius: 75,
    },
    photoPlaceholder: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    photoPlaceholderText: {
        marginTop: 5,
        color: '#777',
    },
    submitButton: {
        backgroundColor: '#007bff',
        borderRadius: 5,
        padding: 15,
        alignItems: 'center',
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    dateButton: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 5,
        padding: 12,
        marginBottom: 15,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    dateButtonText: { fontSize: 16, color: '#333' },
    studentPreview: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f0f8ff',
        padding: 10,
        borderRadius: 5,
        marginBottom: 15,
    },
});

export default styles;